### ISSUE TITLE
I'm having trouble with the references on this

### ISSUE THREAD

**Issue by Taklaminon** [wafflethings/ULTRAKILLtweaker#10]
Alright, so just opening the .sln file in VS gives a sea of yellow triangles in the references section. I tried going the route of "Add References," but I'm not quite prepared to select 100 different dlls individually. I tried just referencing all of the dlls in the "plugins" folder, but that still left out many Unity dlls. How exactly did you go about importing all these references?

**Comment by wafflethings** [comment]
next update will have stripped dlls preincluded and referenced, i asked hakita and he doesnt mind

**Comment by Taklaminon** [comment]
oh thxx
