### ISSUE TITLE
Mod Refuses to Load Properly 

### ISSUE THREAD

**Issue by lukethehound** [wafflethings/ULTRAKILLtweaker#12]
I have been really trying my best to find out what is causing this issue as me and all of my friends have been experiencing the same issue, but alas I am not a code wizard and cannot for the life of me figure out what the hell is going on.

I am currently attempting to run ULTRAKILLtweaker with UMM 0.4.1, as that is the latest version supported, one of two things will happen when me or anyone else that I know of does this.

1: The game fails to boot past the loading screen outright, sending you into a loading screen purgatory.

2: The game will boot to the main menu, but refuses to be enabled; restarting the game projects you back to the loading screen purgatory.

I have also noticed that BepinEx straight-up ignores the mod the majority of the time I do attempt to launch the game with the mod.
![Screenshot_241](https://user-images.githubusercontent.com/118779224/205398228-d92184ea-9892-4629-951a-5e56a346b0cd.png)

I would love for this issue to finally get resolved, as I am really stoked about endlessly messing around with this funky mod!
I hope you are having a good day, and I hope to hear back soon!

**Comment by wafflethings** [comment]
hi sorry

have you tried pressing the checkbox and restarting instead of toggling the mod on

**Comment by lukethehound** [comment]
No worries, happy to hear back from you!

On the off chance that the game does load alongside the mod and does allow me to get to the mod manager menu, checking off the box and then restarting makes the game go back into loading infinitely.

**Comment by lukethehound** [comment]
I ended up trying again after a while and I figured out I just have worm-brain and did some stuff wrong lol

**Comment by mminnt15** [comment]
hey how did you solve this? im still having the issue and ive deleted and redownloaded bepinex and UMM so many times i lost count can you explain what you did?
